window.OFFLINE_PORTFOLIO = {
  profile_info: { id: 1, tagline: "Unemployed Final Boss", bio: " A Full Stack Mobile developer because its convenient device | Builted in 5 days with the help of ShitGPT. | All projects spended 0$ | ((( ADMIN PASSWORD: 2027 ))) | THE REASON WHY I COULD CREATE SOME PROJECT ITS BECAUSE I USE REPLIT, WHEN THE CREDITS WAS END I JUST DELETE MY ACCOUNT AND THE CREDIT WILL RESET AGAIN, However new Update 2026 August was now updated their account deletion, therefore i could no longer create good app again, afterall I just vibecoded, However i could still use gemini using swtiching various account technique, thats what i used on creating UNITY games(Gemini also because it can see video)(But not good as replit where it can view git files code from github)", tech_stack: ["JavaScript","Supabase","Tailwind","SQL","VanillaCSS"], status: "Doom Scrolling", location: "Gingoog City, PH", avatar_url: "offline/portfolio-assets/avatars/1777186180880-RobloxScreenShot20250906_110637097.png" },
  site_settings: { id: 1, life_quote: "If you're going through hell, keep going. Why would you stop in hell?" },
  wisdom_slides: [{ id: 4, text: "If you whant to follow your dream", display_order: 1 }, { id: 5, text: "then don't wake up", display_order: 2 }],
  projects: [
    { id: "0b9e7d0f", title: "Miss Mo", description: "Just a meme, not too much", link: "https://jemjemfromyt.github.io/Miss-mo-/", image_url: "offline/portfolio-assets/projects/1776490323015-Screenshot 2026-04-18 133114.png", languages: "html, css, js", display_order: 15 },
    { id: "2c5aa343", title: "My First Game", description: "This game is something weird, just complete the games i copied from other developer till you finish", link: "https://jemjemfromyt.github.io/Game_code-beta-optimized/", image_url: "offline/portfolio-assets/projects/1776490103111-Screenshot 2026-04-18 132307.png", languages: "html, css, js", display_order: 6 },
    { id: "5e34e417", title: "Pet Quest", description: "If you noticed theres no photo now or cant share or cant upload , thats means the DATABASE which is SUPABASE was Paused, i could easily continue it by clicking CONTINUE, however since no one use this app much so i have to let it pause", link: "https://drive.google.com/file/d/1mMmbMfzLr_1AYi8KXovMg3WNraPpQWt/view?usp=drivesdk", image_url: "offline/portfolio-assets/projects/1782726094822-1000016088.jpg", languages: "kotlin,html,css, supabase", display_order: 1 },
    { id: "711ae934", title: "Mission Uncomfortable", description: "An offline app that gives you mission a day. It will helps you broke the social normies and approxmtely improve confidence without breaking the rules", link: "https://drive.google.com/file/d/1RwslWIbNdoZdWSj0nJJbHIGmamdjQLOp/view?usp=sharing", image_url: "offline/portfolio-assets/projects/1784462267326-Screenshot_20260719_195416.png", languages: "Kotlin", display_order: 2 },
    { id: "788c41c3", title: "Malunggay Pandesal Ai", description: "A Cebuanong Bisaya that can be chat unlimited message and doesn't use API | The downside is very slow to respond so you have wait and vibe with the budots", link: "https://jemjemfromyt-jemjemfromytspace.hf.space", image_url: "offline/portfolio-assets/projects/1777004409372-Screenshot_20260424_115706_Chrome.jpg", languages: "phyton, Flask, HTMX, Hugging Face Spaces, html,css, js", display_order: 4 },
    { id: "7927f09a", title: "ZBaddie", description: "Lol took me 3 weeks to fix this rigging on girl character, BTW this is all about a person who dream stranger", link: "https://drive.google.com/file/d/1QHjEtJQqF0YQ4wdZnCFLN1dOiv6qAlxw/view?usp=drivesdk", image_url: "offline/portfolio-assets/projects/1785998029247-1000016555.jpg", languages: "Unity, C#", display_order: 0 },
    { id: "916b9fd4", title: "8 Souls of J", description: "A playlist of 8 Souls refering to my friends", link: "https://jemjemfromyt.github.io/The-8-Souls/", image_url: "offline/portfolio-assets/projects/1776490207304-Screenshot 2026-04-18 132321.png", languages: "html, css, js", display_order: 6 },
    { id: "a2a379d1", title: "Akong Migo Ai", description: "An Uncensored ai that uses gemini api, it has limit of message. Cannot respond some dangerous intent", link: "https://jemjemfromyt.github.io/Chatbot/", image_url: "offline/portfolio-assets/projects/1776927149086-Screenshot_20260423_145049_Messenger.jpg", languages: "Html,css, js,render,nodejs,json,gemini text", display_order: 3 },
    { id: "a7fdde4b", title: "Dino Vs Alden game V0.3", description: "CAUTIOUS: Please play it only in mobile (and also dont use desktop mode) so that it wont ruin. Built in 3 Days | It was inspired by offline google game but the content is based on my squad", link: "https://jemjemfromyt.github.io/Alden-vs-Jsquad-Dino-V0.4-main/.", image_url: "offline/portfolio-assets/projects/1776489755000-Screenshot 2026-04-18 132103.png", languages: "html, css, js", display_order: 4 },
    { id: "ca6b5e22", title: "Full: Endless Arena Survival Wave", description: "A wave based endless survival where each wave will evolve the enemies, to survive, select a good upgrade of your hero | Multiplayer is available on other mode", link: "https://drive.google.com/file/d/1r_zZH8Bv4JNElcFKty7GXe_Kman5BWb/view?usp=drivesdk", image_url: "offline/portfolio-assets/projects/1777460070204-Screenshot_20260429_185417_Chrome.jpg", languages: "Html, css, js, nodejs, json, paymongo, Android studio", display_order: 1 },
    { id: "e1fd9ed3", title: "JSDied", description: "This game is made of our real house. It inspired by Granny horror mobile game, the characters here I use are my friends that belong to our squad", link: "https://drive.google.com/file/d/1MdvioS0m8h8wCpDZbimgHJMdaB31tGxv/view?usp=drive_link", image_url: "offline/portfolio-assets/projects/1776489977663-Screenshot 2026-04-18 132502.png", languages: "GDScript, Godot", display_order: 2 },
    { id: "feea73d6", title: "Who Is Not The Human", description: "A horror game where you must select the right person", link: "https://jemjemfromyt.github.io/Who-is-not-the-human/", image_url: "offline/portfolio-assets/projects/1776490148127-Screenshot 2026-04-18 132254.png", languages: "html, css, js", display_order: 10 }
  ],
  certificates: [
    { id: "219abaeb", category_name: "Sololearn", title: "Introduction to phyton", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776053878744-Introduction to Python_certificate.jpg" },
    { id: "274a911d", category_name: "JA Philippines - Better Ground Game Development Competition 2026", title: "JA Philippines - Better Ground Game Development Competition 2026", description: "https://drive.google.com/drive/folders/1zUy1RC66vum4gZxJiOU5vzMrpEbDTLo7", image_url: "offline/portfolio-assets/certs/1785998958191-1000016559.jpg" },
    { id: "2ffd4b86", category_name: "Sololearn", title: "Coding foundations", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776148298779-Coding Foundations_certificate.jpg" },
    { id: "429e4751", category_name: "Sololearn", title: "Angular", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776144536191-Angular_certificate (1).jpg" },
    { id: "566c6c9c", category_name: "Sololearn", title: "Web development", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776148311207-Web Development_certificate.jpg" },
    { id: "5fa2ecf2", category_name: "Sololearn", title: "Introduction to css", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776132589362-Introduction to CSS_certificate.jpg" },
    { id: "679a1a0c", category_name: "Sololearn", title: "Phyton Developer", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776053637378-Python Developer_certificate (1).jpg" },
    { id: "7402f300", category_name: "Sololearn", title: "Introduction to html", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776053892567-Introduction to HTML_certificate.jpg" },
    { id: "95e1d974", category_name: "Sololearn", title: "Java intermediate", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776147249042-Java Intermediate_certificate.jpg" },
    { id: "983235f8", category_name: "Sololearn", title: "Front end beginners", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776148323858-Front-end for Beginners_certificate.jpg" },
    { id: "9b434eff", category_name: "Sololearn", title: "Javascript intermediate", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776144401222-JavaScript Intermediate_certificate.jpg" },
    { id: "9b518515", category_name: "Sololearn", title: "Introduction to java", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776147235510-Introduction to Java_certificate.jpg" },
    { id: "a62878dc", category_name: "Sololearn", title: "Introduction to javascript", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776144340243-Introduction to JavaScript_certificate.jpg" },
    { id: "ad09018a", category_name: "Sololearn", title: "C intermediate", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776146088667-C Intermediate_certificate.jpg" },
    { id: "b071bf42", category_name: "Sololearn", title: "Introduction to c#", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776146125368-Introduction to C#_certificate.jpg" },
    { id: "bd3ced13", category_name: "Sololearn", title: "Coding for data", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776148203242-Coding for Data_certificate.jpg" },
    { id: "c7398bc5", category_name: "Sololearn", title: "Introduction to c++", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776053691344-Introduction to C++_certificate (1).jpg" },
    { id: "cf4d8962", category_name: "Sololearn", title: "Introduction to c", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776146043520-Introduction to C_certificate.jpg" },
    { id: "d4eace00", category_name: "Sololearn", title: "Phyton intermediate", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776144386163-Python Intermediate_certificate.jpg" },
    { id: "d8fad73a", category_name: "Sololearn", title: "C# intermediate", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776147223095-C# Intermediate_certificate.jpg" },
    { id: "de250428", category_name: "Sololearn", title: "Introduction to sql", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776144361364-Introduction to SQL_certificate.jpg" },
    { id: "e5b63db1", category_name: "Sololearn", title: "Sql intermediate", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776144496620-SQL Intermediate_certificate.jpg" },
    { id: "f572095b", category_name: "Sololearn", title: "Tech for everyone", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776148182833-Tech for Everyone_certificate.jpg" },
    { id: "f88317e3", category_name: "JA Philippines - Better Ground Game Development Competition 2026", title: "JA Philippines - Better Ground Game Development Competition 2026", description: "https://drive.google.com/drive/folders/1zUy1RC66vum4gZxJiOU5vzMrpEbDTLo7", image_url: "offline/portfolio-assets/certs/1785998931062-1000016438.jpg" },
    { id: "ff3ad6c0", category_name: "Sololearn", title: "C++ intermediate", description: "ACC: https://www.sololearn.com/profile/35533065/?ref=app All languages certs are collected", image_url: "offline/portfolio-assets/certs/1776053849579-C++ Intermediate_certificate.jpg" }
  ],
  hobbies: [
    { id: "d6783686", category: "Anime", title: "Solo Leveling", rank: 1, tags: "S1, S2", description: "Anime I already watched", cover_image: "offline/portfolio-assets/hobbies/1775997716055-images (1).jpeg", show_info: true, show_view: false },
    { id: "a8e0c6fd", category: "Games", title: "Clash Of Clans", rank: 4, tags: "Stopped after got lost the clan because got kicked (Even im the Leader), Started since 2020", cover_image: "offline/portfolio-assets/hobbies/1776497579564-unnamed.png", show_info: true, show_view: true },
    { id: "399689e5", category: "Anime", title: "RE Zero", rank: 4, tags: "S1, S2, S3, S4", cover_image: "offline/portfolio-assets/hobbies/1776493633747-re_zero_kara_hajimeru_isekai_seikatsu_icon_folder_by_mohandor_da76g1j-fullview.png", show_info: true, show_view: false },
    { id: "702d9773", category: "Anime", title: "Black Clover", rank: 2, tags: "S1, S2, S3, S4, The Movies", cover_image: "offline/portfolio-assets/hobbies/1776599868113-MV5BZmZkZjNhMWMtM2U0Mi00MjdlLTk3NmMtMTMwZjgwOTJmODMzXkEyXkFqcGc@._V1_.jpg", show_info: true, show_view: false },
    { id: "99ea0f68", category: "Games", title: "Roblox", rank: 5, tags: "Since 2020", cover_image: "offline/portfolio-assets/hobbies/1776494299698-Roblox_(2025)_(App_Icon).svg.png", show_info: true, show_view: true },
    { id: "c88243c9", category: "Games", title: "Minecraft", rank: 3, tags: "Started Since 2020, Bedrock & Java", cover_image: "offline/portfolio-assets/hobbies/1776291937935-images (5).jpeg", show_info: true, show_view: true },
    { id: "1afdbcc4", category: "Games", title: "Call Of Duty Mobile", rank: 2, cover_image: "offline/portfolio-assets/hobbies/1776497260518-1776044736136-images (2).jpeg", show_info: true, show_view: false },
    { id: "5c1299ce", category: "Games", title: "Mobile Legend", rank: 1, cover_image: "offline/portfolio-assets/hobbies/1776497217234-1776037907456-images.jpeg", show_info: true, show_view: false }
  ],
  socials: [
    { id: "44de24d1", platform: "Instagram", link: "https://www.instagram.com/jemjemfromig?igsh=aTJpcWQ0cnNsNjA1", image_url: "offline/portfolio-assets/socials/1775995778177-pngtree-instagram-icon-png-image_6315974.png", mode: "single", accounts: [] },
    { id: "bd53f988", platform: "Tiktok", link: "https://www.tiktok.com/@jemjemfromyt", image_url: "offline/portfolio-assets/socials/1775995944762-tiktok-logo-tiktok-logo-transparent-tiktok-icon-transparent-free-free-png.png", mode: "multi", accounts: [{ link: "https://www.tiktok.com/@jemjemfromyt", name: "jemjemfromyt", is_main: true }, { link: "https://www.tiktok.com/@jemjemfrom_yt1", name: "jemjemfrom_yt1", is_main: false }] },
    { id: "e116f627", platform: "Facebook", link: "https://www.facebook.com/JemjemfromYT1", image_url: "offline/portfolio-assets/socials/1776044855930-images.png", mode: "multi", accounts: [{ link: "https://www.facebook.com/JemjemfromYT1", name: "James Saavedra" }, { link: "https://www.facebook.com/james.saavedraexe", name: "James SaavedraExe" }, { link: "https://www.facebook.com/profile.php?id=100093410443362", name: "James Saavedraapk", is_main: true }] },
    { id: "f9593bb7", platform: "Youtube", link: "https://youtube.com/@jemjemfromyt1772", image_url: "offline/portfolio-assets/socials/1775996025320-youtube-logo-youtube-social-media-icon-free-png.png", mode: "single", accounts: [] }
  ],
  hobby_gallery: [
    { id: "0a840b23", hobby_id: "99ea0f68", image_url: "offline/portfolio-assets/gallery/1776494558902-3765e563d43aca41a3caf64b17c10372.mp4", media_type: "image" },
    { id: "85537ef4", hobby_id: "99ea0f68", image_url: "offline/portfolio-assets/gallery/1776494632872-Screenshot_20260418_143510_Roblox.jpg", media_type: "image" },
    { id: "a57466c7", hobby_id: "99ea0f68", image_url: "offline/portfolio-assets/gallery/1776494570148-Screenshot_20260418_143738_Roblox.jpg", media_type: "image" },
    { id: "b41c5a70", hobby_id: "c88243c9", image_url: "offline/portfolio-assets/gallery/1776503855569-Screenshot_20260418_171548_Minecraft.jpg", media_type: "image" },
    { id: "bace3e7e", hobby_id: "a8e0c6fd", image_url: "offline/portfolio-assets/gallery/1776497633993-Screenshot_20260418_145953_Clash-of-Clans.jpg", media_type: "image" },
    { id: "d5877d53", hobby_id: "99ea0f68", image_url: "offline/portfolio-assets/gallery/1776494619446-Screenshot_20260418_143945_Roblox.jpg", media_type: "image" },
    { id: "e7ce901a", hobby_id: "1afdbcc4", image_url: "offline/portfolio-assets/gallery/1776497279118-Screenshot_20260418_152411_Call-of-Duty.jpg", media_type: "image" }
  ],
  music: [
    { id: 1, title: "STYX HELIX", artist: "RE Zero", image_url: "offline/portfolio-assets/music/1776319938799-Is-satella-emilia.jpg", audio_url: "offline/portfolio-assets/music/1776319940013-STYX HELIX - MYTH & ROID Official Channel (64k).mp3" },
    { id: 7, title: "The Sacred Torch", artist: "The Faraway Paladin", image_url: "offline/portfolio-assets/music/1776597270534-gracefeel-1-285x400 (1).jpg", audio_url: "offline/portfolio-assets/music/1776597271194-Ytmp3.gg_YouTube_Media_l3kj86i7wQ0_007_128k.mp3" }
  ]
};
